### ISSUE TITLE
Backward compatibility with armv6 (Raspberry Pi Zero)

### ISSUE THREAD

**Issue by marvin5300** [MuonPi/muondetector#62]
Need to add CMakeLists.txt options for armv6
Maybe need to compile daemon for armv6?

**Comment by lnies** [comment]
Currently debugging on Raspberry Py Zero v1.1 WH. 

- Cloning main #51 and not changing anything, building package. Only GUI is being built. GUI seems to start without problems, couldn't test functionality without daemon though yet. Daemon is not built because of 
https://github.com/MuonPi/muondetector/blob/81eefc3bafef4e01d1961e678da4d55d1a156b03/CMakeLists.txt#L18-L21
- This part here probably needs also attention:
https://github.com/MuonPi/muondetector/blob/81eefc3bafef4e01d1961e678da4d55d1a156b03/CMakeLists.txt#L56-L61
- Changing this to `if ("${CMAKE_SYSTEM_PROCESSOR}" MATCHES "^(armv7|armv6)")` as recommended by Daniel, CMake executes w/o problems, but Make runs into following problem (on my Pi):
```
[ 43%] Building CXX object CMakeFiles/muondetector-daemon.dir/daemon/src/pigpiodhandler.cpp.o
/home/pi/muondetector_daemon_binary/muondetector/daemon/src/pigpiodhandler.cpp:13:10: fatal error: pigpiod_if2.h: No such file or directory
   13 | #include <pigpiod_if2.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
````
- This could be system related problem where some libraries are mission. `pigpiod -v` yields `79`, however `sudo apt update && sudo apt install pigpio pigpiod` installs additional packages: `libpigpio-dev libpigpiod-if-dev libpigpiod-if1 pigpio pigpio-tools`. After, I browse for additional packages and also install `libpigpiod-if2-1`. Additionally, `sudo apt-get install file` needs to be installed, as well as `cmake` for building the package.

**Comment by marvin5300** [comment]
Looks like pigpiod include directories have to be installed manually before compiling. Nothing unusual, maybe add it to the list of dependencies when building yourself?

**Comment by lnies** [comment]
Following the steps I outlined in my previous comment, the daemon and the GUI compile under Bullseye on ARMv6 architecture. The compiled daemon can be downloaded here: https://archive.muonpi.org/2.0.2/raspberry_pi_zero_arrmv6/bullseye/muondetector-daemon_2.0.2-hotfix1_armhf.deb. Don't forget to first uninstall and completely remove the daemon from your system first (including the apt key), before installing the downloaded repository with `apt install ./<repo-name>`.

**Comment by gon0** [comment]
Hello everyone,

I have two Raspberry Pi Zero W. I just installed the newest bullseye image and performed `sudo apt update && sudo apt upgrade` as explained here https://wiki.muonpi.org/index.php?title=Raspberry_Pi_Setup .

At the "interfaces" part I enabled Serial and I2C as described. When I "finished" the config, I received this error:

```
pi@raspberrypi:~ $ sudo raspi-config
Created symlink /etc/systemd/system/multi-user.target.wants/vncserver-x11-serviced.service → /lib/systemd/system/vncserver-x11-serviced.service.
modprobe: FATAL: Module i2c-dev not found in directory /lib/modules/5.15.61+

```
although the config displayed:
![grafik](https://user-images.githubusercontent.com/33236024/210117336-c63f6574-df60-44a5-acce-316283c54264.png)

This happened on both Pi Zero W.

What could have gone wrong? Does it make sense to go on with the installation of the muonPis?
